# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TMDB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TMDB
#  pod 'RxSwift'
#  pod 'RxCocoa'
#  pod 'RxRelay'
#  pod 'RxDataSources'
  pod 'youtube-ios-player-helper'
  pod 'Swinject'
  
  target 'TMDBTests' do
    # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!

    # Pods for TMDBTests
#    pod 'RxSwift'
#    pod 'RxCocoa'
#    pod 'RxRelay'
#    pod 'RxDataSources'
    pod 'RxBlocking'
    pod 'RxTest'

  end
end

target 'Domain' do
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxRelay'
  pod 'RxDataSources'

  target 'DomainTests' do
    pod 'RxSwift'
    pod 'RxDataSources'
  end

end

target 'NetworkPlatform' do
  use_frameworks!
  pod 'Swinject'

  target 'NetworkPlatformTests' do
#    pod 'Swinject'
  end

end

